/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThuTh = new javax.swing.JButton();
        btnThuKho = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnThongTin = new javax.swing.JMenu();
        mnDangXuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHƯƠNG TRÌNH QLTV");
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CHƯƠNG TRÌNH QUẢN LÝ THƯ VIỆN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sach/tải xuống.jpg"))); // NOI18N

        btnThuTh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/text.png"))); // NOI18N
        btnThuTh.setText("THỦ THƯ");
        btnThuTh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuThActionPerformed(evt);
            }
        });

        btnThuKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3d bar chart.png"))); // NOI18N
        btnThuKho.setText("THỦ KHO");
        btnThuKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuKhoActionPerformed(evt);
            }
        });

        mnThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        mnThongTin.setText("Thông tin nhóm");
        mnThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnThongTinMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnThongTin);

        mnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        mnDangXuat.setText("Đăng xuất");
        mnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnDangXuat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnThuTh)
                            .addGap(41, 41, 41)
                            .addComponent(btnThuKho))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(33, 33, 33))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThuTh)
                    .addComponent(btnThuKho))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThuThActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuThActionPerformed
        frmThuThu hm = new frmThuThu();
        this.dispose();
        hm.setVisible(true);
    }//GEN-LAST:event_btnThuThActionPerformed

    private void btnThuKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuKhoActionPerformed
        frmThuKho hm = new frmThuKho();
                        this.dispose();
                        hm.setVisible(true);
    }//GEN-LAST:event_btnThuKhoActionPerformed

    private void mnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseClicked
        int hoi = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất không?","Xác nhận", JOptionPane.YES_NO_OPTION);               
        if (hoi == JOptionPane.YES_OPTION) 
        {
            
        
        frmLogin hm = new frmLogin();
                        this.dispose();
                        hm.setVisible(true);
                        }
    }//GEN-LAST:event_mnDangXuatMouseClicked

    private void mnThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThongTinMouseClicked
        frmThongTinNhom hm = new frmThongTinNhom();
                        this.dispose();
                        hm.setVisible(true);
    }//GEN-LAST:event_mnThongTinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThuKho;
    private javax.swing.JButton btnThuTh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnDangXuat;
    private javax.swing.JMenu mnThongTin;
    // End of variables declaration//GEN-END:variables
}
